<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0</TargetFrameworks>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyTitle>Yahoo! Finance Integration</AssemblyTitle>
    <Company>Fairmat SRL</Company>
    <Product>Yahoo! Finance Integration</Product>
    <Copyright>Copyright © Fairmat SRL 2014-2015</Copyright>
    <AssemblyVersion>1.0.7</AssemblyVersion>
    <FileVersion>1.0.7</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\MEFFIntegration\TickerUtility.cs">
      <Link>TickerUtility.cs</Link>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Fairmat.Dvpl.CoreExtensions" />
    <PackageReference Include="Fairmat.Dvpl.DVPLI" />
    <PackageReference Include="Fairmat.Dvpl.DVPLInterfaces" />
    <PackageReference Include="Microsoft.CSharp" />
    <PackageReference Include="Mono.Addins" />
    <PackageReference Include="System.Collections.Immutable" />
    <PackageReference Include="System.Reflection.Emit" />
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>
</Project>