<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0</TargetFrameworks>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyTitle>European Central Bank Integration</AssemblyTitle>
    <Company>Fairmat SRL</Company>
    <Product>European Central Bank Integration</Product>
    <Copyright>Copyright © Fairmat SRL 2013</Copyright>
    <AssemblyVersion>1.0.2</AssemblyVersion>
    <FileVersion>1.0.2</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Fairmat.Dvpl.CoreExtensions" />
    <PackageReference Include="Fairmat.Dvpl.DVPLI" />
    <PackageReference Include="Fairmat.Dvpl.DVPLInterfaces" />
    <PackageReference Include="Mono.Addins" />
    <PackageReference Include="System.Collections.Immutable" />
    <PackageReference Include="System.Memory" />
    <PackageReference Include="System.Numerics.Vectors" />
    <PackageReference Include="System.Reflection.Emit" />
  </ItemGroup>
</Project>