<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8</TargetFrameworks>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyTitle>MarketDataProviders.Tests</AssemblyTitle>
    <Description>Several test for Market Data Providers plugins.</Description>
    <Company>Fairmat SRL</Company>
    <Product>MarketDataProviders.Tests</Product>
    <Copyright>Copyright © Fairmat 2013</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\EuropeanCentralBankExchangeIntegration\EuropeanCentralBankIntegration.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Fairmat.Dvpl.CoreExtensions" />
    <PackageReference Include="Fairmat.Dvpl.DVPLI" />
    <PackageReference Include="Fairmat.Dvpl.DVPLInterfaces" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit.Analyzers" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="System.Reflection.Emit" />
  </ItemGroup>
</Project>